# -*- coding: utf-8 -*-
"""CS5760_Homework2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DekVQIrpu1EKjUweVRIPjlVgCnRZuBl5
"""

from collections import Counter

# Training corpus
corpus = [
    "<s> I love NLP </s>",
    "<s> I love deep learning </s>",
    "<s> deep learning is fun </s>"
]

# Create unigram and bigram counts
unigrams = Counter()
bigrams = Counter()

# Process each sentence
for sentence in corpus:
    words = sentence.split()

    # Count individual words
    unigrams.update(words)

    # Count consecutive word pairs
    bigrams.update(zip(words, words[1:]))

# Calculate MLE bigram probability
def bigram_prob(w1, w2):
    if unigrams[w1] == 0:
        return 0.0

    return bigrams[(w1, w2)] / unigrams[w1]


# Calculate the probability of a sentence
def sentence_prob(sentence):
    words = sentence.split()
    probability = 1.0

    for w1, w2 in zip(words, words[1:]):
        probability *= bigram_prob(w1, w2)

    return probability


# Test sentences
s1 = "<s> I love NLP </s>"
s2 = "<s> I love deep learning </s>"

p1 = sentence_prob(s1)
p2 = sentence_prob(s2)

# Display results
print("Unigram counts:")
print(dict(unigrams))

print("\nBigram counts:")
print(dict(bigrams))

print("\nSentence probabilities:")
print("P(S1) =", p1)
print("P(S2) =", p2)

if p1 > p2:
    print("\nThe model prefers S1 because it has the higher probability.")
else:
    print("\nThe model prefers S2 because it has the higher probability.")

# Save the homework program as a Python source file
code = '''
from collections import Counter

# Training corpus
corpus = [
    "<s> I love NLP </s>",
    "<s> I love deep learning </s>",
    "<s> deep learning is fun </s>"
]

# Create unigram and bigram counts
unigrams = Counter()
bigrams = Counter()

# Process each sentence
for sentence in corpus:
    words = sentence.split()

    # Count individual words
    unigrams.update(words)

    # Count consecutive word pairs
    bigrams.update(zip(words, words[1:]))

# Calculate MLE bigram probability
def bigram_prob(w1, w2):
    if unigrams[w1] == 0:
        return 0.0

    return bigrams[(w1, w2)] / unigrams[w1]


# Calculate the probability of a sentence
def sentence_prob(sentence):
    words = sentence.split()
    probability = 1.0

    for w1, w2 in zip(words, words[1:]):
        probability *= bigram_prob(w1, w2)

    return probability


# Test sentences
s1 = "<s> I love NLP </s>"
s2 = "<s> I love deep learning </s>"

p1 = sentence_prob(s1)
p2 = sentence_prob(s2)

# Display results
print("Unigram counts:")
print(dict(unigrams))

print("\nBigram counts:")
print(dict(bigrams))

print("\nSentence probabilities:")
print("P(S1) =", p1)
print("P(S2) =", p2)

if p1 > p2:
    print("\nThe model prefers S1 because it has the higher probability.")
else:
    print("\nThe model prefers S2 because it has the higher probability.")
'''

with open("homework2.py", "w") as f:
    f.write(code)

print("homework2.py has been created successfully.")